# Generated by Django 3.2.5 on 2021-08-02 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210802_1133'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='customers',
            new_name='Customer',
        ),
        migrations.RenameModel(
            old_name='products',
            new_name='Product',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='tag',
            new_name='tags',
        ),
    ]
